src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinTable;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PostRepository::class)]
#[ORM\Table(name: "posts")]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\Type('string')]
    #[Assert\Length(max: 100, maxMessage: 'Title cannot be longer than 20 characters')]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\Type('string')]
    #[Assert\Length(max: 3000, maxMessage: 'Content cannot be longer than 1000 characters')]
    private ?string $content = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\ManyToOne(inversedBy: 'posts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'likesPosts')]
    private Collection $usersThatLike;

    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'disklikedPosts')]
    private Collection $usersThatDontLike;

    public function __construct()
    {
        $this->usersThatLike = new ArrayCollection();
        $this->usersThatDontLike = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsersThatLike(): Collection
    {
        return $this->usersThatLike;
    }

    public function addUsersThatLike(User $usersThatLike): static
    {
        if (!$this->usersThatLike->contains($usersThatLike)) {
            $this->usersThatLike->add($usersThatLike);
            $usersThatLike->addLikesPost($this);
        }

        return $this;
    }

    public function removeUsersThatLike(User $usersThatLike): static
    {
        if ($this->usersThatLike->removeElement($usersThatLike)) {
            $usersThatLike->removeLikesPost($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsersThatDontLike(): Collection
    {
        return $this->usersThatDontLike;
    }

    public function addUsersThatDontLike(User $usersThatDontLike): static
    {
        if (!$this->usersThatDontLike->contains($usersThatDontLike)) {
            $this->usersThatDontLike->add($usersThatDontLike);
            $usersThatDontLike->addDisklikedPost($this);
        }

        return $this;
    }

    public function removeUsersThatDontLike(User $usersThatDontLike): static
    {
        if ($this->usersThatDontLike->removeElement($usersThatDontLike)) {
            $usersThatDontLike->removeDisklikedPost($this);
        }

        return $this;
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Post;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class)
            ->add('content', TextType::class)
            ->add('save', SubmitType::class, ['label' => 'Save Post'])
            // ->add('created_at')
            // ->add('updated_at')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/Posts/PostsController.php
<?php

namespace App\Controller\Posts;

use App\Entity\Post;
use App\Entity\User;
use App\Form\PostType;
use App\Repository\PostRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Pusher\Pusher;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PostsController extends AbstractController
{

    public function __construct(
        private EntityManagerInterface $em,
        private UserRepository $userRepository,
        private PostRepository $postRepository
    ) {

    }


    public function index(Request $request): Response
    {
        $posts = $this->postRepository->findAllPosts($request->query->getInt('page', 1));
        // dd($posts);
        return $this->render('posts/index.html.twig', [
            'posts' => $posts
        ]);
    }

    public function new(Request $request, Pusher $pusher): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $post = new Post();
        $post->setTitle('write a post title');
        $post->setContent('post content');
        $post->setUser($this->getUser());
        $post->setCreatedAt(new \DateTimeImmutable());
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // $post = $form->getData();
            $this->em->persist($post);
            $this->em->flush();
            $pusher->trigger('my-channel', 'new-post-event', 'New post: <a href="' . $this->generateUrl('posts_show', ["id" => $post->getId()]) . '">' . $post->getTitle() . '</a>');
            return $this->redirectToRoute('posts_index');
        }
        return $this->render('posts/new.html.twig', [
            'form' => $form
        ]);
    }

    public function show(Post $post): Response
    {
        $isFollowing = $this->userRepository->isFollowing(
            $this->getUser(),
            $post->getUser()
        ) ?? false;
        $isLiked = $this->postRepository->isLiked(
            $this->getUser(),
            $post->getId()
        ) ?? false;
        $isDisliked = $this->postRepository->isDisLiked(
            $this->getUser(),
            $post->getId()
        ) ?? false;
        return $this->render('posts/show.html.twig', [
            'post' => $post,
            'isFollowing' => $isFollowing,
            'isLiked' => $isLiked,
            'isDisliked' => $isDisliked
        ]);
    }

    public function edit(Post $post, Request $request): Response
    {
        // $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $this->denyAccessUnlessGranted('POST_EDIT', $post);
        $post->setUpdatedAt(new \DateTimeImmutable('now'));
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $post = $form->getData();
            $this->em->persist($post);
            $this->em->flush();
            return $this->redirectToRoute('posts_index');
        }
        return $this->render('posts/edit.html.twig', [
            'form' => $form
        ]);
    }

    public function delete(Post $post): Response
    {
        // $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $this->denyAccessUnlessGranted('POST_DELETE', $post);
        $this->em->remove($post);
        $this->em->flush();
        return $this->redirectToRoute('posts_index');
    }

    public function user(Request $request, $id): Response
    {
        $posts = $this->postRepository->findAllUserPosts(
            $request->query->getInt('page', 1),
            $id
        );
        return $this->render('posts/index.html.twig', [
            'posts' => $posts,
            'user' => $posts[0]?->getUser()->getName()
        ]);
    }

    public function toggleFollow(User $user, Request $request): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $isFollowing = $this->userRepository->isFollowing(
            $this->getUser(),
            $user
        ) ?? false;
        if ($isFollowing) {
            $this->getUser()->removeFollowing($user);
        } else {
            $this->getUser()->addFollowing($user);
        }
        $this->em->flush();
        $route = $request->headers->get('referer');
        return $this->redirect($route);
    }
}

templates/posts/edit.html.twig
{% extends 'base.html.twig' %}
{% block title %}
Edit post
{% endblock %}
{% block body %}
<div class="my-14">
		<h1 class="text-4xl">Edit blog post</h1>
		<div class="w-full">
			{{ form_start(form, {'attr': {'class': 'bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4' }}
			) }}
				<div class="mb-6">
					{{ form_label(form.title, 'Post title', {'label_attr': {'class': 'block text-gray-700 font-bold mb-2' }}
				) }}
                {% set title_error = form_errors(form.title) ? 'border-red-500 ' : ''%}
					{{ form_widget(form.title, {'attr': {'class': (title_error)~'shadow appearance-none border rounded w-full
            py-2 px-3 text-gray-700 mb-2 leading-tight focus:outline-none focus:shadow-outline','placeholder':'write post content here' }}
				) }}
					{% if form.title.vars['errors']|length > 0 %}
					<p class="text-red-500 text-xs italic">
						{% for error in form.title.vars['errors'] %}
							<span>{{ error.message }}</span>
						{% endfor %}
					</p>
				{% endif %}
				</div>
				<div class="mb-6">
					{{ form_label(form.content, 'Post title', {'label_attr': {'class': 'block text-gray-700 font-bold mb-2' }}
				) }}
                {% set content_error = form_errors(form.content) ? 'border-red-500 ' : '' %}
					{{ form_widget(form.content, {'attr': {'class': (content_error)~'drop-shadow-lg w-full h-60 p-4 border
            focus:outline-none focus:shadow-outline','placeholder':'write post content here'}}) }}
				{% if form.content.vars['errors']|length > 0 %}
					<p class="text-red-500 text-xs italic">
						{% for error in form.content.vars['errors'] %}
							<span>{{ error.message }}</span>
						{% endfor %}
					</p>
				{% endif %}
				</div>
				{{ form_widget(form.save, {'attr': {'class': 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4
        rounded cursor-pointer' }}
			) }}
			{{ form_end(form) }}
		</div>
	</div>
{% endblock %}

templates/posts/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}
	All posts
{% endblock %}
{% block body %}
            {# latest posts #}
            <div class="my-14">
				<h1 class="text-6xl tracking-tighter font-bold mb-6">Latest posts {{ user ?? '' }}
				</h1>
				<p class="mb-8 text-gray-500">A blog created by Maher Ben Rhouma
				</p>
				<hr/>
			</div>

            {# posts #}
			{% for post in posts %}
            <div class="my-14 flex flex-col md:flex-row">
				<p class="mb-8 text-gray-500 mr-20">{{ post.createdAt | date("j M Y") }}</p>
				<div class="space-y-4">
					<h1 class="text-3xl font-bold tracking-tighter">{{post.title}}</h1>
					<p class="text-gray-500">{{ post.content | slice(0,200) ~ '...' }}</p>
					<p>
						<a class="text-red-500 hover:text-red-900 mt-8" href="{{ path('posts_show', {id:post.id, _locale:app.current_route_parameters|last}) }}">Read more</a>
					</p>
					{% if app.user and app.user.id == post.user.id %}
                    <div class="flex">
                    <a href="{{ path('posts_edit', {id:post.id}) }}" title="edit" class="mr-2 cursor-pointer">
                        {{include('svg_icons/edit_icon.html.twig')}}
                    </a>

                    <form method="POST" action="{{ path('posts_delete', {id:post.id}) }}">
                        <button type="submit" href="{{ path('posts_delete', {id:post.id}) }}"
                            onclick="return confirm('Are you sure?')" title="delete" class="cursor-pointer">
                            {{include('svg_icons/delete_icon.html.twig')}}
                        </button>
                    </form>
                </div>
				{% endif %}
				</div>
			</div>
			<hr/>
			{% endfor %}
			<br>
			{{ knp_pagination_render(posts) }}
{% endblock %}
     

templates/posts/new.html.twig
{% extends 'base.html.twig' %}
{% block title %}
	Create a new post
{% endblock %}
{% block body %}
	<div class="my-14">
		<h1 class="text-4xl">New blog post</h1>
		<div class="w-full">
			{# <form method="POST" action="{{ path('posts.new') }}" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"> #}
            {{ form_start(form, {'attr': {'class': 'bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4'}}) }}
				<div class="mb-6">
					{{ form_label(form.title, 'Post title', {'label_attr': {'class': 'block text-gray-700 font-bold mb-2'}}) }}
                    {% set title_error = form_errors(form.title) ? 'border-red-500 ' : ''%}
					{{ form_widget(form.title, {'attr': {'class': (title_error)~'shadow appearance-none border rounded w-full
            py-2 px-3 text-gray-700 mb-2 leading-tight focus:outline-none focus:shadow-outline', 'value':'','placeholder':'write post title here'}}) }}
					{# <p class="text-red-500 text-xs italic">{{ form_errors(form.title) }}</p> #}
                    {% if form.title.vars['errors']|length > 0 %}
                        <p class="text-red-500 text-xs italic">
                            {% for error in form.title.vars['errors'] %}
                            <span>{{ error.message }}</span>
                            {% endfor %}
                        </p>
                    {% endif %}
				</div>
				<div class="mb-6">
					{{ form_label(form.content, 'Post content', {'label_attr': {'class': 'block text-gray-700 font-bold mb-2'}})
				            }}
                    {% set content_error = form_errors(form.content) ? 'border-red-500 ' : '' %}
					{{ form_widget(form.content, {'attr': {'class': (content_error)~'drop-shadow-lg w-full h-60 p-4 border
            focus:outline-none focus:shadow-outline','placeholder':'write post content here'}, 'value':''}) }}
					{# <p class="text-red-500 text-xs italic">{{ form_errors(form.content) }}</p> #}
                    {% if form.content.vars['errors']|length > 0 %}
                        <p class="text-red-500 text-xs italic">
                            {% for error in form.content.vars['errors'] %}
                                <span>{{ error.message }}</span>
                            {% endfor %}
                        </p>
                    {% endif %}
				</div>
				{{ form_widget(form.save, {'attr': {'class': 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4
        rounded cursor-pointer'}}) }}
			{{ form_end(form) }}
		</div>
	</div>
{% endblock %}

templates/posts/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}
	Show a post
{% endblock %}
{% block body %}
<div class="my-14 flex flex-col">
		<div class="text-center">
			<p class="text-gray-500">{{post.createdAt|date("j M Y")}}</p>
			<p class="italic text-sm">by {{post.user.name}}
				<img class="ml-2 object-scale-down h-14 w-14 rounded-full inline" src="http://localhost:8000/images/test-image.png" alt="profile image"></p>

			<h1 class="mb-10 text-6xl font-bold tracking-tighter mt-5">{{post.title}}</h1>
			<hr>
		</div>

		<p class="text-gray-500 mt-10 leading-8">
			{{post.content}}
		</p>

        <div class="flex mt-10">
			{{component('likeComponent',{post:post, isLiked: isLiked,
			isDisliked: isDisliked})}}
            {% if app.user and app.user.id != post.user.id %}
			{% if isFollowing %}
			You follow:&nbsp;<a class="text-green-500 hover:text-green-700" href="{{ path('posts_user', {id:post.user.id}) }}">
				{{post.user.name}}</a>
			{% else %}
			<a href="{{ path('posts_togglefollow', {user:post.user.id}) }}" class="ml-3 inline font-bold text-sm px-6 py-2 text-white rounded bg-blue-500 hover:bg-blue-600">
				Follow the post author</a>
            {% endif %}
			{% endif %}
		</div>

	</div>
{% endblock %}